# Generated by Django 4.2.5 on 2023-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Mention', 'not_mention')], default='Not Mention', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_diabetic',
            field=models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_having_hypertension',
            field=models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_high_cholesterol',
            field=models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_overweight',
            field=models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_recently_injured',
            field=models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_smoking_cigarettes',
            field=models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false'), ('UNKNOWN', 'unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
