# Generated by Django 4.2.7 on 2023-11-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_age_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_insurance_plans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='areas_of_expertise',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='awards_and_recognitions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='board_certifications',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospital_affiliations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_health_care_proffesional',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patient_reviews_and_ratings',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_affiliations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='publications_and_research',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
