# Generated by Django 4.2.7 on 2023-11-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_accepted_insurance_plans_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_health_care_proffesional',
            new_name='is_health_care_professional',
        ),
    ]
